# Generated by Django 3.1.3 on 2020-12-22 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('media_name', models.CharField(max_length=30)),
                ('media_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Media',
            },
        ),
    ]
